language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-ipvs.gemspec
- gem install sensu-plugins-ipvs-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: Hml2ER8xxT9vL2vOAigAWvHh/8PfmaW1bkgpcnxJte6H9VeEfD6Cey+NdHIh7iqfoU5JwxT5a+HiBLmpxQt8jvSLwe9hzLHsuwXSpaEx0dGwVehK8OJNJDvnYpxnsbR8GxlvShY/Rgse6f5qrvK33rwAsE3kavtGpYY5T3Tux0I=
  gem: sensu-plugins-ipvs
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-ipvs
