language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-ipvs.gemspec
- gem install sensu-plugins-ipvs-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: TBHGPkwzKEPG8NaIncOJbbKCKcJJX1PLSqarsYchRkm9bvKhTwOLP1ce43RhdqWCECgeHvuFzb5VMcqMqfiBnSFf6jNNXSXI5xTKCBQBkbasS0dTDfoinnpqwQ8BH7qyh2g+jRCZjslbUaOvuDcGeK7FurHIx1a6aAOXfL0gTps=
  gem: sensu-plugins-ipvs
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-ipvs
